// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuu_xovDb7KEvWgbyhnmbbHwF3czqwLQw',
    appId: '1:962362941256:web:b90a06d2daedb9dc0d9d7d',
    messagingSenderId: '962362941256',
    projectId: 'pigeon-firebase',
    authDomain: 'pigeon-firebase.firebaseapp.com',
    storageBucket: 'pigeon-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDGBEXUN-ytVMIHpw96yDdSLunnG3YueY',
    appId: '1:962362941256:android:de8018673bd2b2200d9d7d',
    messagingSenderId: '962362941256',
    projectId: 'pigeon-firebase',
    storageBucket: 'pigeon-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8VN74-d7E5nHiUq-2QnApY2z43cqJ5Co',
    appId: '1:962362941256:ios:fdcdf22b0deb92fd0d9d7d',
    messagingSenderId: '962362941256',
    projectId: 'pigeon-firebase',
    storageBucket: 'pigeon-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ptpThing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8VN74-d7E5nHiUq-2QnApY2z43cqJ5Co',
    appId: '1:962362941256:ios:fdcdf22b0deb92fd0d9d7d',
    messagingSenderId: '962362941256',
    projectId: 'pigeon-firebase',
    storageBucket: 'pigeon-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ptpThing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuu_xovDb7KEvWgbyhnmbbHwF3czqwLQw',
    appId: '1:962362941256:web:5a54bd1b770282570d9d7d',
    messagingSenderId: '962362941256',
    projectId: 'pigeon-firebase',
    authDomain: 'pigeon-firebase.firebaseapp.com',
    storageBucket: 'pigeon-firebase.firebasestorage.app',
  );

}